const path = require('path')

module.exports = {
  entry:'./src/main.js',
  output:{
    path:path.resolve(__dirname,'dist'),
    filename:'bundle.js',
    publicPath:'dist/'//处理
  },
  module:{
    rules:[
      {
        test:/\.css$/,
        //css-loader只负责将css文件进行加载
        //style-loader负责将样式添加到DOM中
        //使用多个loader时，从右向左
        use:['style-loader','css-loader']
      },
      {
        test:/\.less$/,
        use:[{
          loader:"style-loader"
        },
          {
            loader:"css-loader"
          },
          {
            loader:"less-loader"
          }]
      },
      {
        test:/\.(png|jpg|gif|jpeg)$/,
        options:{
          limit:8192,
          name:'img/[name].[hash:8].[ext]'
        }
      },
      {
        test:/\.js$/,
        exclude:/(node_modules|bower_components)/,
        use:{
          loader:'babel-loader',
          options:{
            preset:['es2015']
          }
        }
      }
    ]
  }
}